# Generated by Django 4.2.4 on 2023-10-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("starmaa", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="People",
        ),
    ]
