# Generated by Django 4.2.4 on 2023-11-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starmaa", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="people",
            name="image",
            field=models.ImageField(null=True, upload_to="people"),
        ),
    ]
